language: java
dist: trusty

env:
  global:
    - GLASSFISH_USER=admin
    - GLASSFISH_PASSWORD=admin
    - GLASSFISH_HOST=localhost
    - GLASSFISH_PORT=4848

jdk:
  - openjdk8

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
  - tar -xzvf apache-maven-3.6.0-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH

install:
  - mvn --version
  
script:
  - mvn clean install
  - asadmin deploy --user $GLASSFISH_USER --password <(echo $GLASSFISH_PASSWORD) target/
