language: java
dist: trusty

jdk:
  - openjdk8


node_js:
  - "16.15.1"

branches:
  except:
    - /^feature.*$/

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
  - tar -xzvf apache-maven-3.6.0-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH

install:
  - mvn --version

script:
  - mvn clean install -U
  - mvn deploy -X --settings deploy/maven-settings.xml
  - mvn sonar:sonar -Dsonar.projectKey=pruebaxcs -Dsonar.host.url=https://ae6b-83-34-101-249.ngrok-free.app -Dsonar.login=2cededaffc1eb5483c04d6ca13256edb98f2865b

