language: java
dist: trusty

env:
  global:
    - GLASSFISH_USER=admin
    - GLASSFISH_PASSWORD=admin
    - GLASSFISH_HOST=localhost
    - GLASSFISH_PORT=4848

jdk:
  - openjdk8

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
  - tar -xzvf apache-maven-3.6.0-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH

install:
  - mvn --version
  
script:
  - mvn clean install
  - mvn sonar:sonar -Dsonar.projectKey=pruebaxcs -Dsonar.host.url=https://b4bf-83-34-97-207.ngrok-free.app -Dsonar.login=2cededaffc1eb5483c04d6ca13256edb98f2865b
  - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.7.1/jfrog-cli-linux-amd64/jfrog
  - chmod +x jfrog
  - ./jfrog rt config --url https://anaxcs.jfrog.io/artifactory --user anaabadlorenzo24@gmail.com --password 131200Anaabad
  - ./jfrog rt u "/home/travis/build/AnaAbadLorenzo/proyectoxcs/ear/target/dgss2324-teamA-microstories-pom-0.1.0.ear" travisci-generic-local --build-name=travisci-generic-artifactory --build-number=1 --flat=false
  - ./jfrog rt bce travisci-generic-artifactory 1
  - ./jfrog rt bp travisci-generic-artifactory 1
